Issue/44 aw data annotations
rvtr/rvtrx-api-lodging pull request #56
Opened 2020-10-30 19:51 UTC by Jonny-Code

resolves #44 and blocker for Campground getting reviews from lodgings objects

2020-10-30 21:25 UTC, escalonn requested changes

2020-10-30 21:25 UTC, escalonn commented on aspnet/RVTR.Lodging.DataContext/Repositories/LodgingRepo.cs
> +      .Include(r => r.Reviews)
document on method, & also below

2020-10-30 21:25 UTC, escalonn commented on aspnet/RVTR.Lodging.DataContext/Repositories/LodgingRepo.cs
> +          if (rental.Status.ToLower().Equals("available") && rental.Unit.Capacity >= occupancy && !filteredLodgings.Contains(item))
use case insensitive equals

2020-10-30 21:25 UTC, escalonn commented on aspnet/RVTR.Lodging.ObjectModel/Models/AddressModel.cs
> +    [RegularExpression(@"(^USA$)|(^US$)")]
error message

2020-10-30 21:25 UTC, escalonn commented on aspnet/RVTR.Lodging.ObjectModel/Models/AddressModel.cs
> +    [MaxLength(50, ErrorMessage = "Street name is too long.")]
higher than 50

2020-10-30 21:25 UTC, escalonn commented on aspnet/RVTR.Lodging.ObjectModel/Models/LocationModel.cs
> +    [RegularExpression(@"^([0-8]{1}?[0-9]{1}(\.\d+)?|90(\.0+)?)[NS]$", ErrorMessage = "Latitude must be in the form 00.0000E")]
clean up regexes

2020-10-30 21:25 UTC, escalonn commented on aspnet/RVTR.Lodging.ObjectModel/Models/LocationModel.cs
> +    [RegularExpression(@"^(1([0-7]{1}[0-9]{1}(\.\d+)?|80(\.0+)?)|([0-9]{2}|[0-9]{1})(\.\d+))[EW]$", ErrorMessage = "Longitude must be in the form 00.0000N")]
EW vs NS

2020-10-30 21:25 UTC, escalonn commented on aspnet/RVTR.Lodging.ObjectModel/Models/LodgingModel.cs
> +    [MaxLength(20, ErrorMessage = "Max length is 20 characters")]
more than 20

2020-10-30 21:25 UTC, escalonn commented on aspnet/RVTR.Lodging.ObjectModel/Models/RentalModel.cs
> +    [RegularExpression(@"^[0-9]?[0-9]?[0-9]?[0-9]?[0-9]$")]
not just digits for this

2020-10-30 21:25 UTC, escalonn commented on aspnet/RVTR.Lodging.ObjectModel/Models/RentalModel.cs
> +    [RegularExpression(@"^\d+(\.\d\d)?$", ErrorMessage = "Price must be in the form 00.00")]
not applicable, check for negative instead

2020-11-03 22:29 UTC, ddowd97 commented on aspnet/RVTR.Lodging.DataContext/Repositories/LodgingRepo.cs
> +      .Include(r => r.Reviews)
Resolved by Alex

2020-11-03 22:29 UTC, ddowd97 commented on aspnet/RVTR.Lodging.DataContext/Repositories/LodgingRepo.cs
> +          if (rental.Status.ToLower().Equals("available") && rental.Unit.Capacity >= occupancy && !filteredLodgings.Contains(item))
Resolved by Alex

2020-11-03 22:29 UTC, ddowd97 commented on aspnet/RVTR.Lodging.ObjectModel/Models/AddressModel.cs
> +    [RegularExpression(@"(^USA$)|(^US$)")]
Resolved by Alex

2020-11-03 22:29 UTC, ddowd97 commented on aspnet/RVTR.Lodging.ObjectModel/Models/AddressModel.cs
> +    [MaxLength(50, ErrorMessage = "Street name is too long.")]
Resolved by Alex

2020-11-03 22:29 UTC, ddowd97 commented on aspnet/RVTR.Lodging.ObjectModel/Models/LocationModel.cs
> +    [RegularExpression(@"^([0-8]{1}?[0-9]{1}(\.\d+)?|90(\.0+)?)[NS]$", ErrorMessage = "Latitude must be in the form 00.0000E")]
Resolved by Alex

2020-11-03 22:29 UTC, ddowd97 commented on aspnet/RVTR.Lodging.ObjectModel/Models/LocationModel.cs
> +    [RegularExpression(@"^(1([0-7]{1}[0-9]{1}(\.\d+)?|80(\.0+)?)|([0-9]{2}|[0-9]{1})(\.\d+))[EW]$", ErrorMessage = "Longitude must be in the form 00.0000N")]
Resolved by Alex

2020-11-03 22:29 UTC, ddowd97 commented on aspnet/RVTR.Lodging.ObjectModel/Models/RentalModel.cs
> +    [RegularExpression(@"^[0-9]?[0-9]?[0-9]?[0-9]?[0-9]$")]
Resolved by Alex

2020-11-03 22:29 UTC, ddowd97 commented on aspnet/RVTR.Lodging.ObjectModel/Models/LodgingModel.cs
> +    [MaxLength(20, ErrorMessage = "Max length is 20 characters")]
Resolved by Alex

2020-11-03 22:29 UTC, ddowd97 commented on aspnet/RVTR.Lodging.ObjectModel/Models/RentalModel.cs
> +    [RegularExpression(@"^\d+(\.\d\d)?$", ErrorMessage = "Price must be in the form 00.00")]
Resolved by Alex

2020-11-03 22:33 UTC, markmoorerev approved these changes

2020-11-03 22:35 UTC, markmoorerev approved these changes

2020-11-03 22:40 UTC, escalonn approved these changes

2020-11-03 22:40 UTC, escalonn commented on aspnet/RVTR.Lodging.ObjectModel/Models/RentalUnitModel.cs
> +    [RegularExpression(@"^\d+ ?([Ff]t|[Yy]ards|[Mm]eters|[Mm]) ?x ?\d+ ?([Ff]t|[Yy]ards|[Mm]eters|[Mm])$", ErrorMessage = "Size must be in the form '10 [unit?] x 10 [unit?]'")]
this is probably a bit over specific but fine

2020-11-03 22:53 UTC, merged