RentalUnitModel-folded
rvtr/rvtrx-api-lodging pull request #80
Opened 2021-02-11 16:54 UTC by elmertsai

2021-02-11 22:36 UTC, JTLaMarre commented
included in bulk pull can close this, all pulls failing testing.

2021-02-12 21:12 UTC, fredbelotte requested changes
fix any changes affecting the tests.

2021-02-16 22:11 UTC, fredbelotte commented
is this PR still valid?

2021-02-16 22:21 UTC, elmertsai commented
No, please close this PR if you can... it was created on accident during our first push

2021-02-17 19:36 UTC, closed without merging